formulaforce/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTEST-{0000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

formulaforce/force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be contestants in a race</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers whose status is Active are permitted</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

formulaforce/force-app/main/default/objects/Contestant__c/fields/Qualification1LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification1LapTime__c</fullName>
    <label>Qualification 1 Lap Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

formulaforce/force-app/main/default/objects/Contestant__c/fields/Qualification2LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification2LapTime__c</fullName>
    <label>Qualification 2 Lap Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

formulaforce/force-app/main/default/objects/Contestant__c/fields/Qualification3LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification3LapTime__c</fullName>
    <label>Qualification 3 Lap Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

formulaforce/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

formulaforce/force-app/main/default/objects/Driver__c/fields/DriverId__c.field-meta.xml
<CustomField>
    <fullName>DriverId__c</fullName>
    <label>Driver Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

formulaforce/force-app/main/default/objects/Driver__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>Finnish</fullName>
            </value>
            <value>
                <fullName>Mexican</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

formulaforce/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

formulaforce/force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

formulaforce/force-app/main/default/classes/SeasonService.cls
public with sharing class SeasonService 
{
	
	public static void issueNewsLetterCurrentSeason() {
		throw new SeasonServiceException('Not implemented');
	}

	public static void issueNewsLetters() {
		throw new SeasonServiceException('Not implemented');
	}

	public static void updateStandings(Set<Id> seasonIds) {
		throw new SeasonServiceException('Not implemented');
	}

	public static void updateStandings(List<UpdateStandings> updateStandings) {
		throw new SeasonServiceException('Not implemented');
	}

	public static void importSeason(String jsonData) {
		// Parse JSON data
		System.debug(jsonData);
		SeasonsData seasonsData = 
			(SeasonsData) JSON.deserializeStrict(jsonData, SeasonService.SeasonsData.class);

		// Construct a Unit of Work to capture the following working
		fflib_IsObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

		Map<String, Driver__c> driversById = new Map<String, Driver__c>();
		for(DriverData driverData : seasonsData.drivers) {
			// Create Driver__c record
			Driver__c driver = new Driver__c(
				Name = driverData.name,
				DriverId__c = driverData.driverId,
				Nationality__c = driverData.nationality,
				TwitterHandle__c = driverData.twitterHandle
			);
			// add to Unit of Work
			uow.registerNew(driver);
			driversById.put(driver.DriverId__c, driver);
		}

		for(SeasonData seasonData : seasonsData.seasons) {
			// Create Season__c record
			Season__c season = new Season__c(
				Name = seasonData.year,
				Year__c = seasonData.year
			);
			// add to Unit Of Work
			uow.registerNew(season);

			for (RaceData raceData : seasonData.races) {
				// Create Race__c record
				Race__c race = new Race__c(Name = raceData.name);
				// add to Unit of Work and link race to season
				uow.registerNew(race, Race__c.Season__c, season);
				for(ContestantData contestantData : raceData.contestants) {
					// Create Contestant__c record
					Contestant__c contestant = new Contestant__c(
						RacePosition__c = contestantData.racePosition,
						ChampionshipPoints__c = contestantData.championshipPoints,
						DNF__c = contestantData.dnf,
						Qualification1LapTime__c = contestantData.qualification1LapTime,
						Qualification2LapTime__c = contestantData.qualification2LapTime,
						Qualification3LapTime__c = contestantData.qualification3LapTime
					);
					// Add to Unit Of Work and establish links to Race & Driver
					uow.registerNew(contestant, Contestant__c.Race__c, race);
					uow.registerRelationship(contestant, Contestant.Driver__c, 
						driversById.get(contestantData.driverId));
				}
			}
		} // end for season...

		// Insert records registered with uow above
		uow.commitWork();
	}

	public class SeasonServiceException extends Exception {}

	public class UpdateStandings {
		public Id seasonId;
		public Boolean issueNewsLetter;

	}

	public class SeasonsData {
		public List<DriverData> drivers;
		public List<SeasonData> seasons;
	}

	public class DriverData {
		public String name;
		public String nationality;
		public String driverId;		
		public String twitterHandle;		

	}

	public class SeasonData {
		public String year;
		public List<RaceData> races;
	}

	public class RaceData {
		public Integer round;
		public String name;
		public List<ContestantData> contestants;
	}

	public class ContestantData {
		public String driverId;
		public Integer racePosition;
		public Integer championshipPoints;
		public Boolean dnf;
		public Integer qualification1LapTime;
		public Integer qualification2LapTime;
		public Integer qualification3LapTime;
	}

}